In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

### Data Preprocessing 

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df=df.iloc[:,3:]

In [6]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [7]:
def GenderBinary(value):
    if value == 'Female':
        return 0
    else:
        return 1
    

In [8]:
df['Gender'] = df['Gender'].apply(lambda x : GenderBinary(x))

In [9]:
df.head(5)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [10]:
dum = pd.get_dummies(df['Geography'])

In [11]:
dum.head()

France  Germany  Spain
0       1        0      0
1       0        0      1
2       1        0      0
3       1        0      0
4       0        0      1

In [12]:
df['France'] = dum['France']
df['Germany'] = dum['Germany']
df['Spain'] = dum['Spain']

In [13]:
df.drop('Geography',axis=1,inplace=True)

In [14]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  France  Germany  Spain  
0               1        101348.88       1       1        0      0  
1               1        112542.58       0       0        0      1  
2               0        113931.57       1       1        0      0  
3               0         93826.63       0       1        0      0  
4               1         79084.10       0       0        0      1

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = df.drop('Exited',axis=1)
y= df['Exited']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Freature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [20]:
X_train = sc.fit_transform(X_train)

In [21]:
X_test = sc.transform(X_test)

### Neural Net

In [22]:
import keras

/home/pranav/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [37]:
from keras.models import Sequential

In [38]:
from keras.layers import Dense

In [39]:
classifier = Sequential()

In [40]:
classifier.add(Dense(units=6,activation='relu',kernel_initializer='uniform',input_dim=12))

In [41]:
classifier.add(Dense(units=6,activation='relu',kernel_initializer='uniform'))

In [42]:
classifier.add(Dense(units=1,activation='sigmoid',kernel_initializer='uniform'))

In [43]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [44]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 3s 410us/step - loss: 0.4790 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 270us/step - loss: 0.4296 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 261us/step - loss: 0.4251 - acc: 0.7964
Epoch 4/100
8000/8000 [==============================] - 2s 262us/step - loss: 0.4207 - acc: 0.8175
Epoch 5/100
8000/8000 [==============================] - 2s 260us/step - loss: 0.4174 - acc: 0.8260
Epoch 6/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.4155 - acc: 0.8289
Epoch 7/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.4130 - acc: 0.8292
Epoch 8/100
8000/8000 [==============================] - 2s 259us/step - loss: 0.4118 - acc: 0.8332
Epoch 9/100
8000/8000 [==============================] - 2s 263us/step - loss: 0.4109 - acc: 0.8344
Epoch 10/100
8000/8000 [==============================] - 2s 265us/step - loss: 0.4096 - acc: 0.8339

8000/8000 [==============================] - 2s 274us/step - loss: 0.3957 - acc: 0.8366
Epoch 83/100
8000/8000 [==============================] - 2s 262us/step - loss: 0.3951 - acc: 0.8362
Epoch 84/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.3954 - acc: 0.8375
Epoch 85/100
8000/8000 [==============================] - 2s 254us/step - loss: 0.3956 - acc: 0.8375
Epoch 86/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.3958 - acc: 0.8367
Epoch 87/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.3955 - acc: 0.8342
Epoch 88/100
8000/8000 [==============================] - 2s 262us/step - loss: 0.3957 - acc: 0.8362
Epoch 89/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.3953 - acc: 0.8355
Epoch 90/100
8000/8000 [==============================] - 2s 265us/step - loss: 0.3953 - acc: 0.8365
Epoch 91/100
8000/8000 [==============================] - 2s 258us/step - loss: 0.3958 - acc: 0.8361
Epo

In [45]:
y_pred = classifier.predict(X_test)

In [49]:
y_pred[:10]

array([[0.20687462],
       [0.32612312],
       [0.17490837],
       [0.05272338],
       [0.1798795 ],
       [0.8518091 ],
       [0.14916268],
       [0.0806643 ],
       [0.15614995],
       [0.87071496]], dtype=float32)

In [50]:
y_pred = (y_pred>0.5)

In [51]:
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]])

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
print(confusion_matrix(y_test,y_pred))

[[1536   59]
 [ 246  159]]
